hiddenSize2 = 50;
autoenc2 = trainAutoencoder(feat1,hiddenSize2, ...
    'MaxEpochs',1000, ...
    'L2WeightRegularization',0.010, ...
    'SparsityRegularization',4, ...
    'SparsityProportion',0.36, ...
    'UseGPU',true,...
    'ScaleData', false);

feat2 = encode(autoenc2,feat1); 