hiddenSize4 = 30;
autoenc4 = trainAutoencoder(feat3,hiddenSize4, ...
    'MaxEpochs',1000, ...
    'L2WeightRegularization',0.002, ...
    'SparsityRegularization',4, ...
    'SparsityProportion',0.36, ...
    'UseGPU',true,...
    'ScaleData', false);
feat4 = encode(autoenc3 , feat3) ;